#include("integrate.jl")
include("../src/precursor.jl")
include("../src/matchpeaks.jl")
include("../src/PSM_TYPES/FastXTandem.jl")
include("../src/getPrecursors.jl")
include("../src/binaryRangeQuery.jl")
include("precursor.jl")

include("../src/applyMods.jl")
include("applyMods.jl")
include("../src/Routines/PRM/IS-PRM_SURVEY/buildPrecursorTable.jl")
include("./Routines/PRM/IS-PRM-Survey/buildPrecursorTable.jl")
include("matchpeaks.jl")
include("binaryRangeQuery.jl")
include("PSM_TYPES/FastXTandem.jl")
#include("./PSM_TYPES/FastXTandem.jl")
#include("getPrecursors.jl")