name = "PioneerParamsApp"
uuid = "b801e2bc-f004-44fc-b633-43da3a1a8185"
version = "0.7.4"
authors = ["Nathan Wamsley", "Dennis Goldfarb"]

[deps]
PioneerParams = "fc87d0e0-10c0-40c1-9f6d-0d6a27f22e8d"

[sources]
PioneerParams = { path = "../../packages/PioneerParams" }

[compat]
julia = "1.12"
